'use client';

import React, { useMemo, useState } from 'react';
import Link from 'next/link';
import { ExternalLink, GraduationCap, MapPin, Search } from 'lucide-react';
import colleges from '@/data/colleges.json';

export default function CollegesPage() {
  const [search, setSearch] = useState('');
  const [state, setState] = useState('All');
  const [ownership, setOwnership] = useState('All');
  const states = ['All', ...Array.from(new Set(colleges.map((c) => c.state))).sort()];
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return colleges.filter((c) => (state === 'All' || c.state === state) && (ownership === 'All' || c.ownership === ownership) && (!q || [c.name,c.city,c.state,c.type,...c.courses,...c.acceptedExams].join(' ').toLowerCase().includes(q))); }, [search,state,ownership]);

  return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
    <section className="rounded-3xl bg-gradient-to-r from-slate-950 via-purple-950 to-slate-950 text-white p-7 sm:p-10 shadow-xl"><div className="text-purple-300 text-xs font-bold uppercase tracking-wider flex items-center gap-2"><GraduationCap className="w-4 h-4" /> India College Discovery</div><h1 className="mt-3 text-3xl sm:text-5xl font-black">Government & Private Colleges</h1><p className="mt-3 text-sm text-slate-300 max-w-3xl">Search a growing nationwide directory by state, ownership, city, course and entrance route. Use official institution websites for current admissions, fees and deadlines.</p></section>
    <section className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm space-y-4"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search IIT, NIT, medical, private, engineering, Bengaluru..." className="w-full pl-9 pr-4 py-3 rounded-xl border border-slate-300 outline-none focus:ring-2 focus:ring-purple-500 text-sm"/></div><div className="flex flex-wrap gap-2"><select value={state} onChange={(e)=>setState(e.target.value)} className="px-3 py-2 rounded-xl border border-slate-300 text-xs font-semibold"><option>All</option>{states.slice(1).map((s)=><option key={s}>{s}</option>)}</select><select value={ownership} onChange={(e)=>setOwnership(e.target.value)} className="px-3 py-2 rounded-xl border border-slate-300 text-xs font-semibold"><option>All</option><option>Government</option><option>Private</option></select><div className="text-xs text-slate-500 font-bold self-center">{filtered.length} institutions</div></div></section>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{filtered.map((college)=> <article key={college.id} className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm hover:shadow-lg hover:border-purple-300 transition"><div className="flex items-center justify-between"><span className="px-2.5 py-1 rounded-full bg-purple-50 text-purple-700 text-[10px] font-black">{college.ownership}</span><span className="text-[10px] text-slate-500 font-semibold">{college.type}</span></div><h2 className="mt-4 text-lg font-black text-slate-900">{college.name}</h2><p className="mt-1 text-xs text-slate-500 flex items-center"><MapPin className="w-3.5 h-3.5 mr-1"/>{college.city}, {college.state}</p><div className="mt-4"><div className="text-[10px] uppercase font-black text-slate-400">Popular programs</div><div className="flex flex-wrap gap-1 mt-2">{college.courses.slice(0,4).map((c)=><span key={c} className="text-[10px] bg-slate-100 rounded px-2 py-1 text-slate-700 font-semibold">{c}</span>)}</div></div><div className="mt-4"><div className="text-[10px] uppercase font-black text-slate-400">Entrance routes</div><div className="text-xs text-slate-700 font-semibold mt-1">{college.acceptedExams.join(' • ')}</div></div><div className="mt-5 pt-4 border-t border-slate-100 flex items-center justify-between gap-3"><Link href={`/colleges/${college.id}`} className="text-xs font-black text-purple-600 hover:underline">View details →</Link><a href={college.website} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-[10px] font-bold text-slate-500">Official <ExternalLink className="w-3 h-3"/></a></div></article>)}</div>
    {filtered.length===0 && <div className="py-16 text-center text-slate-500 text-sm">No colleges matched your filters.</div>}
  </div>;
}
