import Link from 'next/link';
import { ArrowLeft, ExternalLink, GraduationCap, MapPin } from 'lucide-react';
import colleges from '@/data/colleges.json';

export default function CollegeDetailPage({ params }: { params: { collegeId: string } }) {
  const college = colleges.find((item) => item.id === params.collegeId);
  if (!college) return <div className="max-w-3xl mx-auto px-4 py-16 text-center"><h1 className="text-2xl font-black">College not found</h1><Link href="/colleges" className="inline-block mt-4 text-purple-600 font-bold">Back to Colleges</Link></div>;
  return <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-7"><Link href="/colleges" className="inline-flex items-center gap-1 text-xs font-bold text-slate-500"><ArrowLeft className="w-4 h-4"/> Back to College Directory</Link><section className="rounded-3xl bg-slate-950 text-white p-7 sm:p-10"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-purple-500/20 text-purple-200 px-2.5 py-1 text-[10px] font-black">{college.ownership}</span><span className="rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-bold">{college.type}</span></div><h1 className="mt-4 text-3xl sm:text-5xl font-black">{college.name}</h1><p className="mt-2 text-sm text-slate-300 flex items-center"><MapPin className="w-4 h-4 mr-2"/>{college.city}, {college.state}</p></section><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><Info title="Programs" items={college.courses}/><Info title="Entrance / admission routes" items={college.acceptedExams}/><section className="bg-white border border-slate-200 rounded-2xl p-6"><h2 className="font-black text-slate-900">Admission checklist</h2><ol className="mt-4 space-y-3 text-xs text-slate-700 list-decimal list-inside"><li>Check the official programme eligibility.</li><li>Confirm the current entrance route and counselling process.</li><li>Verify tuition, hostel and other fees from the institution.</li><li>Confirm current deadlines before applying.</li></ol></section><section className="bg-purple-50 border border-purple-100 rounded-2xl p-6"><h2 className="font-black text-slate-900">Official source</h2><p className="mt-2 text-xs text-slate-600">EduPath uses the institution website as the authoritative place to confirm current admissions and fee information.</p><a href={college.website} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 px-4 py-2.5 bg-purple-600 text-white rounded-xl text-xs font-bold">Open Official Website <ExternalLink className="w-4 h-4"/></a></section></div></div>;
}
function Info({title,items}:{title:string;items:string[]}) { return <section className="bg-white border border-slate-200 rounded-2xl p-6"><div className="flex items-center gap-2"><GraduationCap className="w-4 h-4 text-purple-600"/><h2 className="font-black text-slate-900">{title}</h2></div><div className="mt-4 flex flex-wrap gap-2">{items.map((x)=><span key={x} className="px-3 py-1.5 rounded-lg bg-slate-100 text-xs font-semibold text-slate-700">{x}</span>)}</div></section>; }
